### PR TITLE
Fixes #224 (Allow user options to be passed to ghc-modi)

### LINKED ISSUE #224: ghc-modi tool: Allow custom flags other than legacy-interactive
Hey there!

Great job on this plugin, keep it up!

I wanted to give it a serious shot for work, but I'm having some problems with ghc-modi, but it's orthogonal to this issue. I want to force other flags in the ghc-modi section other than `legacy-interactive`, but this lines of code seems to completely wipe and replace the content with legacy-interactive only:

https://github.com/carymrobbins/intellij-haskforce/blob/05cac21377bdd9242dd3bd27f222ba5deea5bcb6/src/com/haskforce/settings/HaskellToolsConfigurable.java#L343

Do you think it would make sense to simply append `legacy-interactive` rather than overriding everything?

Thanks!

Alfredo

### PR DESCRIPTION
**Pull request by adinapoli**
reviewer @carymrobbins 

As said in the comments, the only fishy thing of this PR are those extra lines added to the *.iml, which I feel shouldn't be there.

Other than that I have tested the plugin locally and indeed it exhibits the desired behaviour.

### CODE REVIEW

**Comment by carymrobbins** [comment]
Thanks!  A few things -

1. Could you squash these changes?
2. Don't add the `.iml` files
3. Wrap the if block in `{ curly braces }` (I need to put up at least a small style guide)
4. Don't include the version bump, I may just include some other work from the wip branch on the next release.

I'd do these myself, but I'd like to retain your name for your work in the commit history.

**Comment by adinapoli** [comment]
@carymrobbins Hey, no problem -- the iml files looked fishy anyway, and as I'm accustomed to do `git add --all` anyway they end up cropping up in the commit.

I will do all these tweaks this evening (again, missed the hacking-window again for this morning :wink: )

**Comment by adinapoli** [comment]
@carymrobbins We should be in business. I have no clue though why GH thinks I have modified those .iml after I have reverted all of them. Go figure.

**Comment by carymrobbins** [comment]
@adinapoli - It looks like it's just the line endings.  You probably have IntelliJ set to add line feeds to the end of your files (as do I) so it's doing that.  You could probably get around it by doing something like
```
$ git reset HEAD -- <files>
```
But those files should really have line endings anyway, so it's not really a big deal.

**Comment by adinapoli** [comment]
I give up. Starting on a fresh branch.

**Pull request closed without merging**
