### PR TITLE
Cabal parser and lexer working

### PR DESCRIPTION
**Pull request by KasperJanssens**
Cary,

This is the first part of the cabal stuff I've been talking about now (code generates on the correct place now, the culprit was the existing CabalParser.java file in the source code), lots of changes  but mostly generated files. This should just parse and lex. There will be other branches with Haskell references also finding cabal references (rename of haskell module renames export module in cabal) and movement (movement of haskell file -> renames exported module in cabal, and will also rename the imports to the new directory and so on and so forth). So, two more branches to go, but likely not today anymore ;-).  This supersedes the other PR. As always, when unclear, doubts, it sucks, the hangout ;-).

Kasper

### CODE REVIEW

**Comment by carymrobbins** [comment]
Nice!  I'll try to take a look at it tonight.

**Comment by carymrobbins** [comment]
@KasperJanssens -

When editing it seems that syntax highlighting was a little flaky, particularly when trying different indentation levels.  But even upon typing `executable ..` the highlighting doesn't seem to kick in.

screenshot from 2015-04-16 20 28 13

Other than that, the parse tree looks pretty nice.  I am currently working on getting better cabal integration (importing a project, adding cabal packages, cabal init, etc.) and this will really help with that.

Have you tried applying the parser to both the new and old cabal formats?  It's probably not a huge deal, until it is.

Oh, and nice work!

**Comment by carymrobbins** [comment]
Here's an excerpt that seems to act funny.

1. It doesn't seem to like the `.` for `hs-source-dirs` (here I am pulling in the root directory and the `app` directory as sources).
  * Possibly we need to either allow freefiorm text or split on spaces (I don't think cabal supports paths with spaces per the definition of *token, filename, directory* in the [Cabal User Guide](https://www.haskell.org/cabal/users-guide/developing-packages.html)).
2. If I remove the `.` then `OverloadedStrings` gets an error.
  * Again, `extensions` should either allow freeform or split on newlines (and trim spaces).

Ideally, the values for both `hs-source-dirs` and `extensions` should be parsed into lists so they can be traversed easily.

Other words of wisdom - I'd make the parser *really* lenient.  Bugs in the Haskell parser are usually resolved by making it less strict.  I personally don't think it's our parser's job to validate the cabal file, we can probably tap into cabal for that (just like we tap into GHC for Haskell validation).  We need to make sure that we can recover from virtually any scenario and continue parsing the file; otherwise, any features dependent upon the parse result will fail.  And many times, it's simply because our parser is being too strict (and wrong).

```cabal
library
    exposed-modules: Foo
                     Bar
    if flag(dev)
        hs-source-dirs: . app
        exposed-modules: DevelMain
        build-depends:   resourcet              >= 1.1      && < 1.2
                       , process                >= 1.2      && < 1.3
                       , foreign-store          >= 0.1      && < 0.2

    if flag(dev) || flag(library-only)
        cpp-options:   -DDEVELOPMENT
        ghc-options:   -Wall -fwarn-tabs -O0
    else
        ghc-options:   -Wall -fwarn-tabs -O2

    extensions: TemplateHaskell
                QuasiQuotes
                OverloadedStrings
                NoImplicitPrelude
                MultiParamTypeClasses
                TypeFamilies
                GADTs
                GeneralizedNewtypeDeriving
                FlexibleContexts
                EmptyDataDecls
                NoMonomorphismRestriction
                DeriveDataTypeable
                ViewPatterns
                TupleSections
                RecordWildCards
```

**Comment by KasperJanssens** [comment]
I agree on the words of wisdom, the only thing is that the more lenient we are with formats, the more difficult it gets in code to count on the content being usable. For example, if we would treat the exported-modules as free text, it would be impossible to use it in 'resolve' stuff (the next branch). So, I thought the approach to be : start strict and relax along the way. But maybe this is inviting lots of issues of course, and I'll have to re-evaluate the approach, especially if it takes you about five seconds to break it ;-). As well, we're not really being helped by the fact that the best cabal documentation seems to the haskell implementation of cabal (oh the joy), they sometimes tell blatantly wrong things in that documentation, forget keywords, ....

**Comment by KasperJanssens** [comment]
Concerning the highlighting, I don't know it has this behaviour, I also noticed it already, you have an idea? The difference between haskell and cabal here is that I only have one parser for syntax highlighting and parsing. So, the syntax highlighting parser is too complex for what it really needs to be.  The reason to have one was basically laziness and not seeing a reason to have two. But maybe this weird behaviour is the reason of course.

**Comment by carymrobbins** [comment]
I actually would like to unify the Haskell lexers, as time goes on I become less happy with having two as it complicates things.  Every time I update one I have to basically copy and paste the code into the other.  There might be a way to compose them, but I don't think JFlex supports that kind of thing out of the box.

I haven't really debugged this issue yet, but I have ran into similar issues before.  I think we've gotten around it before by using an Annotator.  Here's an example commit from an old issue (#10) which resolves a bug with multi-line string highlighting - https://github.com/carymrobbins/intellij-haskforce/commit/9d70b603cda8f6794b927ffc551b9b4d84ee5b7c#diff-f5acbc6f260265e414d34d9078c40884

**Comment by carymrobbins** [comment]
I'm not sure why the build was passing without this, but we need to update `build.xml` for this as well -

```diff
-  <property name="jflex.cabalHighlight.target.base" value="src/com/haskforce/cabal/highlighting/_CabalSyntaxHighlightingLexer"/>
+  <property name="jflex.cabalHighlight.target.base" value="src/com/haskforce/cabal/psi/_CabalParsingLexer"/>
```

**Comment by KasperJanssens** [comment]
It passes because I left skeletons of that SyntaxHighlighting stuff in it, I wasn't sure what they were for exactly (the two different lexer and parsers) so I didn't want to go too brutal. Git could have helped me there as well, but with the mass of commits I had finding the correct commit to roll back would have been more painful than just leaving these stubgs in and maybe re-adding their flesh afterwards. I'll rename the xml statements and drop the classes , and I'll try to address your problem with the . in hs source files, going to make a free text field out of it.
Concerning the Annotator, there is a CabalAnnotator as well, I think you created it and I changed it enough to make it compile after changing the lexer, but I didn't understand its significance, and as no tests were getting broken I figured it would be okay. Of course, if it's about performance of the lexer, then I might have broken it by changing it.

**Comment by carymrobbins** [comment]
I tried to open [ghc-mod's cabal file](https://github.com/kazu-yamamoto/ghc-mod/blob/master/ghc-mod.cabal) and it could not parse the `License-Files` section.

```
  KEY_OR_CONFIG
    KEY
      LICENSE_FILES
        PsiElement(CabalTokenType.license-files)('License-Files')
        PsiElement(CabalTokenType.:)(':')
  PsiElement(CabalTokenType.varidRegexp)('COPYING')
  PsiElement(CabalTokenType..)('.')
  PsiElement(CabalTokenType.varidRegexp)('BSD3')
  PsiElement(CabalTokenType.varidRegexp)('COPYING')
  PsiErrorElement:'.' unexpected
    PsiElement(CabalTokenType..)('.')
  PsiElement(DUMMY_BLOCK)
    PsiElement(DUMMY_BLOCK)
      PsiElement(CabalTokenType.varidRegexp)('AGPL3')
      PsiElement(CabalTokenType.homepage)('Homepage')
      PsiElement(CabalTokenType.:)(':')
```

I tried to update the `licenseFiles` rule to use `freeform` instead of `<<commaSeparate fileName>>` but that didn't seem to work either -

```
  KEY_OR_CONFIG
    KEY
      LICENSE_FILES
        PsiElement(CabalTokenType.license-files)('License-Files')
        PsiElement(CabalTokenType.:)(':')
  PsiErrorElement:CabalTokenType.Synthetic rightbrace or CabalTokenType.freeformRegexp expected, got 'COPYING'
    PsiElement(CabalTokenType.varidRegexp)('COPYING')
  PsiElement(DUMMY_BLOCK)
    PsiElement(DUMMY_BLOCK)
      PsiElement(CabalTokenType..)('.')
      PsiElement(CabalTokenType.varidRegexp)('BSD3')
```

We should grab a bunch of popular projects' cabal files and add them to the test suite.  Also, we should make sure that all of the keys that we are parsing have a test case.  Unless we have a specific use case, I would say don't worry too much about parsing stuff perfectly.  For stuff like exposed-modules, extensions, etc. it makes sense.  But license-files, for example, is probably not something we really need to deal with just yet.

Once this is ready to merge we should do a final rebase and have the generated files in a separate commit to make the _actual_ changes a bit clearer.

**Comment by KasperJanssens** [comment]
I agree, I already tried to get as much cabal files in, as well as tests for all keys in cabal (but possibly I never tried with multiple keys, or I didn't use dots or whatever). I'll try to fix it, freeform should work. You're right, the license files key contains useless info for us so it can easily be freeform. More suggestions about open source cabal files you'd like tested? Lens, feldspar and my own pet project are already in there for example.

**Comment by carymrobbins** [comment]
Oh, completely missed that you included those.

Looking at some popular ones would probably be good.  For instance, I'd probably just copy all of the ones from this page -

https://github.com/search?utf8=%E2%9C%93&q=language%3AHaskell&type=Repositories&ref=advsearch&l=Haskell

Yesod itself is particularly complex and actually consists of a bunch of separate projects, so there's a bunch there to throw in.

I don't mean to make this more complicated, but the Haskell parser gets in our users' way a lot and I want to make sure not to compound the issue.  This looks like we're getting pretty close to merging and honestly I'm excited for it.

**Comment by KasperJanssens** [comment]
Sure, no problem, I think it's a good idea and I wasn't sure on how far we'd have to take it. It'll take some time to get that done most likely, I'll try my very best to go for it this weekend, it was going to rain here anyway ;-). Did you happen to have a chance to check the other PR's in the mean time?

**Comment by carymrobbins** [comment]
@KasperJanssens - Since I now have builds working with Scala, we could probably port [GHC's Cabal parser] and have the ADTs extend from IntelliJ's PSI classes.  If something like that proves to be successful, we might be able to pull that off with the Haskell parser as well.  Thoughts?

**Comment by KasperJanssens** [comment]
It seems surely the way to go, although I'm a bit unsure how exactly, as it would take integrating Haskell calls from within Java, no? Can you give a small example on how you think we could pull this off?

**Comment by carymrobbins** [comment]
@KasperJanssens - It doesn't seem like we could _directly_ port the Cabal parser to a PsiParser, but I do have a preliminary Cabal parser implemented in Scala now without the use of Grammar Kit, and at the moment it seems like a way better way to write a parser - see commit https://github.com/carymrobbins/intellij-haskforce/commit/49886bac5a1f3a41131eb9b88331dd171ee7405b

For now I'm going to close this PR and its descendants.  Once the parser is written we'll be able to determine whether the other PRs can apply.  At the very least we can probably use a lot of the logic, particularly those that add go to symbol and intentions.

**Pull request closed without merging**
