### PR TITLE
Architecture abstractions

### LINKED ISSUE #298: Architecture
I don't feel confident building the GHCi integration right now, haskforce is a bit of an jungle.
I am trying to document the classes, but its not easy.
To really build a clean, simple GHCi module, we need modularise things.
There are currently 20 packages and a few classes in `src.haskforce` and its really hard to understand the relationships between them. For example cabal is partly modularised (there is a cabal-package), but the actions are in actions.cabal and there are some classes like CabalExecutor in the utils package.

### LINKED ISSUE #305: Discover Cabal Packages should handle root accordingly
I was testing the Discover Cabal Packages action on a sample project that i have just imported (not via stack).
It has the normal structure you get by calling `stack new <name>`
`
src/
ExampleProject.cabal
stack.yaml
`
now calling Discover Cabal Packages leads to declaring the some weird configuration where most of my files disappear (including the src/ directory).

### PR DESCRIPTION
**Pull request by LeanderK**
This is the second pull request to close #298, there first one being #306.

These are a lot of commits, so what have i done?
1. I created a new packages-package in the system-package, where information about BuildInfos, GHC-Version etc is obtainable in a documented, non Package-Manager-dependent way. This also allows abstractions like project-setup where i create modules and mark directories. This is useful to for example StackProjectImport-Action, AddCabalPackage-Action, DiscoverCabalProjects-Action etc. 
   **Finished**
2. I created a integrations-package where interfaces reside to interact with the haskell-support (highlighting etc.). **Finished**
3. cabal got an major overhaul, the implementation of the packages mechanism for cabal and the replacement of the query-package. **Finished**
4. ghcmod to factored out of the haskell-package. It now mostly implements interfaces from the system-package and interacts with the haskell-package rarely. **Finished**
5. hindent just got moved into its own package, no big deal. **Finished**
6. hlint also got mostly moved with some minor modifications like the integration with the packages-system. **Finished**
7. stack got a minor overhaul, it now implements the packages mechanism and got some integration with the new API, like StackProjectImport. **Finished**
8. stylishhaskell also got mostly moved  **Finished**
9. yesod got mostly moved **Finished**

looking back at this tone of work, i think it was worth it. I think the project gets much more manageable with these changes, functionality for the tools is not scattered around, but grouped into (mostly) independent packages. Also the introduction of the system-package grouped the relevant (and hopefully good documented) classes if one is willing to extend the functionality of haskforce.

There are also some small improvements to haskforce:
1. Haskforce now fully initialises the modules (source-dir/tests etc.) for the DiscoverCabal/AddCabal Actions
2. It fixes #305
3. and many smaller ones

there are now some low-hanging fruits, so i will probably create a few pull-requests after this is done that closes the tickets that are now easy to implement.
# it is not ready to merge yet

### CODE REVIEW

**Comment by LeanderK** [comment]
i plan on finishing it in the next few, days. I will also write a more detailed summary.

**Comment by LeanderK** [comment]
after chatting with one of the jetbrain guys i realised that i made a mistake in designing the packages-package (what a name!). IDEs are complicated.

**Comment by LeanderK** [comment]
if somebody wants to help, these are some tasks that can be in relative isolation:
- [ ] reordering of the tests. Currently the tests do not reflect the package structure of the plugin.
- [ ] documenting system.integrations. System.integrations is the glue between haskell and the tools, mostly XYfactories dragged out of the haskell-package. These should be documented.

**Comment by LeanderK** [comment]
the only thing thats missing is some version migration code and the documentation mentioned above

**Comment by LeanderK** [comment]
i want to play with it a bit, to see if i missed something. But then it's ok to merge. Already started playing with #308, this should be really easy now.

**Comment by carymrobbins** [comment]
Closing this for now as it hasn't been updated in a while. I'm still open to cleaning up the package layout and have some ideas about how to go about this moving forward, so feel free to reach out if you'd like to discuss.

**Pull request closed without merging**
