### PR TITLE
Strictness annotations in GADT constructors.

### PR DESCRIPTION
**Pull request by robeverest**
GADT constructors with strictness annotations currently don't parse. e.g.

```haskell
data Test where
  Test :: {-# UNPACK #-} !Int -> Test
```

This fixes that by making the parsing grammar more closely match GHC's. There's a test case for it as well.

### CODE REVIEW

**Comment by pjonsson** [comment]
We are not using the same parsing technology as GHC so replacing one grammar with the other doesn't generally work. GHC also filters out the extra programs that their lenient parser admits in later stages but we don't have that extra filtering and implementing it is a fair bit of work.

**Comment by robeverest** [comment]
I see your point. This does make the parser slightly more lenient than desired. i.e. Strictness annotations can be inserted into type signatures like so

```haskell
foo :: {-# UNPACK #-} !Int -> Bool
```

which is clearly invalid. 

However, the parser also accepts other cases where annotations are used incorrectly. For example

```haskell
foo _ = {-#INLINE b #-} False
```

is accepted by the parser as well. So I guess the question is how lenient should the parser be?

An alternative to my approach would be to parse the LHS of GADT constructors separately from types in general. This would result in some duplication in the grammar, as the only way the two differ is one has strictness annotations and the other doesn't. I would be happy to do this, if that's what you think would be best?

**Comment by carymrobbins** [comment]
Honestly, I generally feel that making the parser more lenient is a good thing so long as its data is easily accessible.  In the case of an IDE, we want to be able to handle mistakes fine and let GHC do the real error checking.

**Comment by carymrobbins** [comment]
Merged, thanks @robeverest!

**Pull request closed without merging**
