### PR TITLE
Fix new haskell project untitled name

### PR DESCRIPTION
**Pull request by charleso**
There's probably a better way?

### CODE REVIEW

**Comment by carymrobbins** [comment]
Looking at the source of [ProjectSettingsStep.updateDataModel](https://github.com/JetBrains/intellij-community/blob/master/java/idea-ui/src/com/intellij/ide/projectWizard/ProjectSettingsStep.java#L189) it seems like `myNamePathComponent.getNameValue()` is the culprit.

It seems that the `updateDataModel` is getting called twice - once for the [common finishing step that IntelliJ automatically adds](https://github.com/JetBrains/intellij-community/blob/master/java/idea-ui/src/com/intellij/ide/projectWizard/NewProjectWizard.java#L55) and again for our "modified" step.  So just _not_ calling `super.updateDataModel` very well might be the way here, although, it does seem strange.  The fact that IntelliJ forces you to have this common finishing step is kind of strange in the first place, [see where I've complained about this before](https://devnet.jetbrains.com/message/5546817#5546817).

**Comment by charleso** [comment]
>  So just not calling super.updateDataModel very well might be the way here, although, it does seem strange.

Yeah, it's very strange. I was hoping there was a cleaner way - I fear this is the kind of hack that comes back to bite later when they change the internals.

**Comment by carymrobbins** [comment]
Alternatively, I was looking into extending from `ModuleWizardStep` instead, avoiding the need to call the `super` method.  That does require defining a `getComponent`, but I'm not yet sure how exactly it's used.  Better figure out how this works under the hood to fix it right.

**Comment by carymrobbins** [comment]
Ok, reading more IntelliJ source makes things a little clearer.  In looking at [ModuleBuilder](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/ide/util/projectWizard/ModuleBuilder.java#L128-L138) it seems that `modifySettingsStep` is really wanting a _"callback"_ (which is really the class `ModuleWizardStep`) that provides the `validate` and `updateDataModel` methods.

So, extending from `ProjectSettingsStep` is a little silly and a better base class would indeed be `ModuleWizardStep`.  However, as I mentioned before, that requires defining `getComponent`, which is not used for anything, so we _could_ just return `null`, [which is also exactly what the default implementation does](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/ide/util/projectWizard/ModuleBuilder.java#L155-L157).  But yeah, still smells funny.  But it really does seem to be the best way.  Check out commit https://github.com/carymrobbins/intellij-haskforce/commit/d18a6b12b162ffe9be7de4694bc6d5247d188e5c.

**Comment by charleso** [comment]
@carymrobbins Agree that it both smells funny, but also seems better than extending from `ProjectSettingsStep`. I'm curious what what other plugins do to work around this. Feel free to close this PR if you have your change on another branch.

**Comment by carymrobbins** [comment]
It seems pretty much every project does something slightly different.  I went ahead with commit 97ce95bdce76772964d766f88a8c6cc16a2ee634 which should take care of the issue.

Thanks for catching this!

**Pull request closed without merging**
